apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-store.fullname" . }}
  labels:
    {{- include "online-store.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "online-store.selectorLabels" . | nindent 4 }}
